# Generated by Django 5.2.4 on 2025-07-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AUTHOR", "Author"),
                            ("LIBRARIAN", "Librarian"),
                            ("VISITOR", "Visitor"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
