# Generated by Django 5.2.4 on 2025-07-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("librarians", "0001_initial"),
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("published_date", models.DateField()),
                ("days_remaining", models.DateField()),
                ("is_available", models.BooleanField()),
                (
                    "author",
                    models.ManyToManyField(
                        related_name="books_written", to="authors.author"
                    ),
                ),
                (
                    "borrowed_by",
                    models.ManyToManyField(
                        related_name="books_borrowed", to="visitors.visitor"
                    ),
                ),
                (
                    "issued_by",
                    models.ManyToManyField(
                        related_name="books_issued", to="librarians.librarian"
                    ),
                ),
            ],
        ),
    ]
