# Generated by Django 5.2.4 on 2025-07-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="borrowed_by",
        ),
        migrations.RemoveField(
            model_name="book",
            name="days_remaining",
        ),
        migrations.RemoveField(
            model_name="book",
            name="issued_by",
        ),
    ]
